polar:
  catalog-service-uri: http://catalog-service
spring:
  flyway:
    url: jdbc:postgresql://polar-postgres/polar_db_order
  r2dbc:
    url: r2dbc:postgresql://polar-postgres/polar_db_order
  rabbitmq:
    host: polar-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://polar-keycloak/realms/PolarBookshop
