apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: order-service
          image: ghcr.io/fofanaabou/order-service
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8082
          env:
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polar_db_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polar_db_order
          livenessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: order-config-volume
              mountPath: /workspace/config
      volumes:
        - name: order-config-volume
          configMap:
            name: order-config

      imagePullSecrets:
        - name: registry-secret
